Fix Vala external preview (#169)
If there was no original id - Vala preview would fail with

> No UI definition loaded yet.

because of

> Error: Expected type string for argument 'string' but got type
undefined